global:
  scrape_interval: 10s
scrape_configs:
  - job_name: VM
    metrics_path: /metrics
    static_configs:
      - targets: [ '192.168.80.10:9100' ]
  
  - job_name: Containers
    static_configs:
      - targets: [ '192.168.80.10:8080' ]