version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - my_network

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - my_network

volumes:
  postgres_data:

networks:
  my_network:
    external: true
